# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: uat
      POSTGRES_PASSWORD: localdbonly
      POSTGRES_DB: uat
    volumes:
      - ~/.uat/postgres:/var/lib/postgresql/data

  uat:
    image: uat
    restart: always
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - 9000:9000
    volumes:
      - ./universal-application-tool-0.0.1:/code
    build: .
    command: sbt ~run
