# Mount code for hot reloading and cache for faster compile in dev mode.
version: '3.1'

services:

  civiform:
    build: .
    volumes:
      - ./universal-application-tool-0.0.1:/usr/src/universal-application-tool-0.0.1
      - ~/.coursier:/root/.coursier
      - ~/.sbt:/root/.sbt
      - ~/.ivy:/root/.ivy2
