AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  S3VPCEndpoint:
    Description: The vpc endpoint from which UAT connects to S3.
    Type: String
Resources:
  key:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: The key used to encrypt/decrypt secure uploads to the UAT.
      KeySpec: SYMMETRIC_DEFAULT
      KeyPolicy:
        Version: '2012-10-17'
        Id: secureuploads-key
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS:
              Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - :root
          Action: kms:*
          Resource: '*'
  bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt key.Arn
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        # This totally prevents anyone outside the AWS account using this bucket.
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Delete
  bucketpolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref bucket
      PolicyDocument:
        Statement:
          - Sid: Restrict access to VPC endpoint
            Action:
              - 's3:*'
            Effect: Deny
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref bucket
                - /*
            Principal: '*'
            Condition:
              StringNotEquals:
                'aws:sourceVpce': !Ref 'S3VPCEndpoint'
Outputs:
  bucketname:
    Description: The location of the bucket for secure uploads.
    Value: !Ref bucket
    Export:
      Name: !Sub '${AWS::StackName}-SecureBucket'