name: ci

on:
  push:
    branches: main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run tests
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: uat:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
