name: pr_test

on:
  pull_request:
    branches: main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out pr branch
        uses: actions/checkout@v2
        with:
          path: pr
      - name: Run tests in tester
        uses: ./pr/.github/actions/test
        with:
          path: pr/
